<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite51f7e1e05b3e30d3828f86ab9850d95
{
    public static $files = array (
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInite51f7e1e05b3e30d3828f86ab9850d95::$classMap;

        }, null, ClassLoader::class);
    }
}
